name: hlint

on:
  pull_request:
  push:

jobs:
  build:
    name: hlint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up HLint
      uses: haskell/actions/hlint-setup@v2
      with:
        version: "3.3.6"

    - name: Run Hlint
      uses: haskell/actions/hlint-run@v2
      with:
        path: '["src/", "test/"]'
        fail-on: suggestion